<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_LazyImageLoader
 * @author     Extension Team
 * @copyright  Copyright (c) 2018-2019 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<?php // @codingStandardsIgnoreFile  ?>
<?php
/**
 * LazyImageLoader block
 *
 * @var  $block  \Bss\LazyImageLoader\Block\LazyLoad
 */
?>
<?php
$helper = $block->getHelper();
echo $helper->getFullActionName();
$threshold = $helper->getThreshold();
?>
<?php if ($helper->isEnabled()) : ?>
    <style>
        img.lazy {
            background: url(<?php echo $helper->getLazyImage(); ?>) no-repeat;
            background-size: <?php echo $helper->getLoadingWidth(); ?>px;
            background-position: center;
            width: 100%
        }
    </style>

    <script type="text/x-magento-init">
        {
            "*": {
                "Bss_LazyImageLoader/js/lazy_load": {
                    "threshold": "<?php echo $threshold; ?>"
                }
            }
        }
    </script>

<?php endif; ?>
