<?php
/** @var \Magento\Framework\View\Element\Template $block */
?>
<head data-content-type="html-head" data-appearance="default" data-element="main">
    <?= $block->getChildHtml('meta') ?>
    <?= $block->getChildHtml('title') ?>
    <?= $block->getChildHtml('css') ?>
    <?= $block->getChildHtml('head.additional') ?>
    <?= $block->getChildHtml('head.components') ?>
    <?= $block->getChildHtml('require.js') ?>


  


</head>
